---
  extends: eslint:recommended

  env:
    es2020: true

  parserOptions:
    # ecmaVersion: 2020
    sourceType: module

  # parser: babel-eslint


  rules:

    # Best Practices

    semi: [2, never]

    curly: [2, multi-line]
    comma-dangle: [2, always-multiline]
    no-use-before-define: [2, nofunc]

    no-loop-func: 1 # should allow arrow function

    accessor-pairs: 2
    complexity: [2, 32]
    consistent-return: 2
    default-case: 2
    dot-notation: 2
    eqeqeq: 2
    no-else-return: 2
    no-eval: 2
    no-empty-label: 2
    no-floating-decimal: 2


    # Strict Mode

    strict: [2, global]
    global-strict: 0


    # Consistence

    quotes: [2, single, avoid-escape]
    new-cap: [2, capIsNew: false]

    no-underscore-dangle: 0
    new-parens: 0


    # ES6+

    no-var: 2
    prefer-const: 2
    no-const-assign: 2
    no-class-assign: 2

    constructor-super: 2
    no-this-before-super: 2
    no-dupe-class-members: 2

    prefer-arrow-callback: 2
    prefer-spread: 2
    prefer-reflect: 2
    prefer-template: 2
    object-shorthand: 1 # buggy
    require-yield: 1

    arrow-parens: [2, as-needed]
    arrow-spacing: 2
    generator-star-spacing: 1 # buggy for babel async


    # Extra

    no-proto: 1
    no-constant-condition: 1

    no-multiple-empty-lines: 2
    indent: [2, tab]
